### ISSUE TITLE
 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 

### ISSUE THREAD

**Issue by MatthewTt** [ErKeLost/unplugin-imagemin#19]
```shell
 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 16 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
```
mode: `Squoosh`
Hot to fix?

**Comment by ErKeLost** [comment]
This should be a squoosh concurrent multithreading warning problem, which will be fixed in the next version. Please make sure that your plug-in version is always up to date, because when adapting to vite4.x, a version will be released almost tomorrow.

**Comment by ErKeLost** [comment]
> 

After my attempt, I found that this warning does not solve the problem of squoosh, which should trigger this phenomenon in some computers or scenarios. The initialization of event listeners is defined inside squoosh, so it does not solve this problem very well. 

Thank you very much for your use.
