### ISSUE TITLE
Unable to compress image in background-image url("")

### ISSUE THREAD

**Issue by aShu-guo** [ErKeLost/unplugin-imagemin#35]
If it were written like this, can be compressed

```vue
<template>
    <div class='main-box' :style="{ backgroundImage: `url(${Background})` }"></div>
</template>
<script setup>
import Background from '@/assets/images/home-background.png';
</script>
<style>
.main-box{
  background-size:100%;
}
</style>
``` 

But that doesn't work
 
```vue
<template>
    <div class='main-box'></div>
</template>
<script setup></script>
<style>
.main-box{
  background-image: url('@/assets/images/home-background.png');
  background-size:100%;
}
</style>
```

Is this normal?

**Comment by ErKeLost** [comment]
Can you provide your imagemin configuration file? I'll check it out.

**Comment by aShu-guo** [comment]
```javascript
const config = {
    // Default mode squoosh. support squoosh and sharp
    mode: 'squoosh',
    // Default configuration options for compressing different pictures
    compress: {
      jpg: {
        quality: 0,
      },
      jpeg: {
        quality: 70,
      },
      png: {
        quality: 70,
      },
      webp: {
        quality: 70,
      },
    },
    conversion: [
      { from: 'png', to: 'webp' },
      { from: 'jpeg', to: 'webp' },
    ],
  }
```

**Comment by ErKeLost** [comment]
> ```js
> const config = {
>     // Default mode squoosh. support squoosh and sharp
>     mode: 'squoosh',
>     // Default configuration options for compressing different pictures
>     compress: {
>       jpg: {
>         quality: 0,
>       },
>       jpeg: {
>         quality: 70,
>       },
>       png: {
>         quality: 70,
>       },
>       webp: {
>         quality: 70,
>       },
>     },
>     conversion: [
>       { from: 'png', to: 'webp' },
>       { from: 'jpeg', to: 'webp' },
>     ],
>   }
> ```

Thank you. I'll check.

**Comment by ErKeLost** [comment]
> ```js
> const config = {
>     // Default mode squoosh. support squoosh and sharp
>     mode: 'squoosh',
>     // Default configuration options for compressing different pictures
>     compress: {
>       jpg: {
>         quality: 0,
>       },
>       jpeg: {
>         quality: 70,
>       },
>       png: {
>         quality: 70,
>       },
>       webp: {
>         quality: 70,
>       },
>     },
>     conversion: [
>       { from: 'png', to: 'webp' },
>       { from: 'jpeg', to: 'webp' },
>     ],
>   }
> ```

You can temporarily add `beforeBundle: false` to config to solve this problem.

**Comment by ErKeLost** [comment]
> > ```js
> > const config = {
> >     // Default mode squoosh. support squoosh and sharp
> >     mode: 'squoosh',
> >     // Default configuration options for compressing different pictures
> >     compress: {
> >       jpg: {
> >         quality: 0,
> >       },
> >       jpeg: {
> >         quality: 70,
> >       },
> >       png: {
> >         quality: 70,
> >       },
> >       webp: {
> >         quality: 70,
> >       },
> >     },
> >     conversion: [
> >       { from: 'png', to: 'webp' },
> >       { from: 'jpeg', to: 'webp' },
> >     ],
> >   }
> > ```
> 
> You can temporarily add `beforeBundle: false` to config to solve this problem.

```ts
    imagemin({
      // Default mode squoosh. support squoosh and sharp
      mode: 'sharp',
      beforeBundle: false,
      // Default configuration options for compressing different pictures
      compress: {
        jpg: {
          quality: 50,
        },
        jpeg: {
          quality: 70,
        },
        png: {
          quality: 70,
        },
        webp: {
          quality: 70,
        },
      },
      conversion: [
        { from: 'png', to: 'webp' },
        { from: 'jpeg', to: 'webp' },
      ],
    }),
```

**Comment by ErKeLost** [comment]
> > > ```js
> > > const config = {
> > >     // Default mode squoosh. support squoosh and sharp
> > >     mode: 'squoosh',
> > >     // Default configuration options for compressing different pictures
> > >     compress: {
> > >       jpg: {
> > >         quality: 0,
> > >       },
> > >       jpeg: {
> > >         quality: 70,
> > >       },
> > >       png: {
> > >         quality: 70,
> > >       },
> > >       webp: {
> > >         quality: 70,
> > >       },
> > >     },
> > >     conversion: [
> > >       { from: 'png', to: 'webp' },
> > >       { from: 'jpeg', to: 'webp' },
> > >     ],
> > >   }
> > > ```
> > 
> > 

 You can temporarily add `beforeBundle: false` to config to solve this problem.
At present, it is because vite does not parse this url module. What version of vite are you using?
It is recommended that mode choose sharp. Squoosh is unstable.
I found a lot of problems in the latest version with squoosh

> 
> ```ts
>     imagemin({
>       // Default mode squoosh. support squoosh and sharp
>       mode: 'sharp',
>       beforeBundle: false,
>       // Default configuration options for compressing different pictures
>       compress: {
>         jpg: {
>           quality: 50,
>         },
>         jpeg: {
>           quality: 70,
>         },
>         png: {
>           quality: 70,
>         },
>         webp: {
>           quality: 70,
>         },
>       },
>       conversion: [
>         { from: 'png', to: 'webp' },
>         { from: 'jpeg', to: 'webp' },
>       ],
>     }),
> ```

**Comment by ErKeLost** [comment]
> > > > ```js
> > > > const config = {
> > > >     // Default mode squoosh. support squoosh and sharp
> > > >     mode: 'squoosh',
> > > >     // Default configuration options for compressing different pictures
> > > >     compress: {
> > > >       jpg: {
> > > >         quality: 0,
> > > >       },
> > > >       jpeg: {
> > > >         quality: 70,
> > > >       },
> > > >       png: {
> > > >         quality: 70,
> > > >       },
> > > >       webp: {
> > > >         quality: 70,
> > > >       },
> > > >     },
> > > >     conversion: [
> > > >       { from: 'png', to: 'webp' },
> > > >       { from: 'jpeg', to: 'webp' },
> > > >     ],
> > > >   }
> > > > ```
> 
> You can temporarily add `beforeBundle: false` to config to solve this problem. At present, it is because vite does not parse this url module. What version of vite are you using? It is recommended that mode choose sharp. Squoosh is unstable. I found a lot of problems in the latest version with squoosh

You can try using the following configuration
> 
> > ```ts
> >     imagemin({
> >       // Default mode squoosh. support squoosh and sharp
> >       mode: 'sharp',
> >       beforeBundle: false,
> >       // Default configuration options for compressing different pictures
> >       compress: {
> >         jpg: {
> >           quality: 50,
> >         },
> >         jpeg: {
> >           quality: 70,
> >         },
> >         png: {
> >           quality: 70,
> >         },
> >         webp: {
> >           quality: 70,
> >         },
> >       },
> >       conversion: [
> >         { from: 'png', to: 'webp' },
> >         { from: 'jpeg', to: 'webp' },
> >       ],
> >     }),
> > ```

**Comment by ErKeLost** [comment]
> > > > > ```js
> > > > > const config = {
> > > > >     // Default mode squoosh. support squoosh and sharp
> > > > >     mode: 'squoosh',
> > > > >     // Default configuration options for compressing different pictures
> > > > >     compress: {
> > > > >       jpg: {
> > > > >         quality: 0,
> > > > >       },
> > > > >       jpeg: {
> > > > >         quality: 70,
> > > > >       },
> > > > >       png: {
> > > > >         quality: 70,
> > > > >       },
> > > > >       webp: {
> > > > >         quality: 70,
> > > > >       },
> > > > >     },
> > > > >     conversion: [
> > > > >       { from: 'png', to: 'webp' },
> > > > >       { from: 'jpeg', to: 'webp' },
> > > > >     ],
> > > > >   }
> > > > > ```
> > 
> > 





 You can temporarily add `beforeBundle: false` to config to solve this problem. At present, it is because vite does not parse this url module. What version of vite are you using? It is recommended that mode choose sharp. Squoosh is unstable. I found a lot of problems in the latest version with squoosh
> 
> You can try using the following configuration
> 
> > > ```ts
> > >     imagemin({
> > >       // Default mode squoosh. support squoosh and sharp
> > >       mode: 'sharp',
> > >       beforeBundle: false,
> > >       // Default configuration options for compressing different pictures
> > >       compress: {
> > >         jpg: {
> > >           quality: 50,
> > >         },
> > >         jpeg: {
> > >           quality: 70,
> > >         },
> > >         png: {
> > >           quality: 70,
> > >         },
> > >         webp: {
> > >           quality: 70,
> > >         },
> > >       },
> > >       conversion: [
> > >         { from: 'png', to: 'webp' },
> > >         { from: 'jpeg', to: 'webp' },
> > >       ],
> > >     }),
> > > ```

**Comment by aShu-guo** [comment]
thank you very much! The version I am using is vite@3.2.5. But i think vite already fix it.

[issue#3980](https://github.com/vitejs/vite/issues/3980)

**Comment by ErKeLost** [comment]
I'll try vite3.2. I can use version 4.x.
