### ISSUE TITLE
The paths are not detected correctly when build

### ISSUE THREAD

**Issue by TiroZit** [ErKeLost/unplugin-imagemin#41]
### Steps to reproduce

The html pages are stored in the path src/views
When building your plugin, it thinks they are stored in the src root

### What is expected?

I have pages stored in the path src/views, when I build it it gives an error because unplugin-imagemin/vite thinks that the pages are in the root of dist, but in fact the pages are in dist/views when I build it

### What is actually happening?

![image](https://user-images.githubusercontent.com/78494774/230435364-fbe98010-a457-4e34-a9be-9b3fa0e33454.png)

### System Info

```shell
nodejs v16.16.0 (64-bit)
```

**Comment by ErKeLost** [comment]
Thank you for your use. Can I write a demo so that I can better troubleshoot errors?

**Comment by ErKeLost** [comment]
Ok, let me check the problem

**Comment by ErKeLost** [comment]
I'm sorry. I only have time recently. I'll release a version.

**Comment by censujiang** [comment]
I have same question

**Comment by ErKeLost** [comment]
I'm sorry I've been busy lately. I'll check this problem as soon as possible.
