### ISSUE TITLE
undefined file

### ISSUE THREAD

**Issue by isliqian** [ErKeLost/unplugin-imagemin#54]
### Steps to reproduce

<img width="999" alt="image" src="https://github.com/ErKeLost/unplugin-imagemin/assets/29324161/100c6b6e-fb33-41ed-acb7-dda2d2006ba9">

imagemin({
            // Default mode squoosh. support squoosh and sharp
            mode: 'sharp',
            // Default configuration options for compressing different pictures
            compress: {
                jpg: {
                    quality: 70,
                },
                jpeg: {
                    quality: 70,
                },
                png: {
                    quality: 70,
                },
                webp: {
                    quality: 70,
                },
            },
            // The type of picture converted after the build
            conversion: [
                { from: 'png', to: 'jpeg' },
                { from: 'jpeg', to: 'webp' },
            ]
        })

### What is expected?

<img width="321" alt="image" src="https://github.com/ErKeLost/unplugin-imagemin/assets/29324161/c3572695-3faa-4ced-a6ee-74c4b54d8975">

### What is actually happening?

??

**Comment by ErKeLost** [comment]
Can you provide a simple demo? I will solve this problem as soon as possible.

**Comment by ErKeLost** [comment]
> ### Steps to reproduce
> <img alt="image" width="999" src="https://user-images.githubusercontent.com/29324161/257098771-100c6b6e-fb33-41ed-acb7-dda2d2006ba9.png">
> imagemin({ // Default mode squoosh. support squoosh and sharp mode: 'sharp', // Default configuration options for compressing different pictures compress: { jpg: { quality: 70, }, jpeg: { quality: 70, }, png: { quality: 70, }, webp: { quality: 70, }, }, // The type of picture converted after the build conversion: [ { from: 'png', to: 'jpeg' }, { from: 'jpeg', to: 'webp' }, ] })
> 
> ### What is expected?
> <img alt="image" width="321" src="https://user-images.githubusercontent.com/29324161/257098996-c3572695-3faa-4ced-a6ee-74c4b54d8975.png">
> ### What is actually happening?
> ??
> 
> ### System Info
> _No response_
> 
> ### Any additional comments?
> _No response_

You can try adding an attribute again. `beforeBundle: true`

**Comment by isliqian** [comment]
<img width="350" alt="image" src="https://github.com/ErKeLost/unplugin-imagemin/assets/29324161/de6c1c3b-edf5-4264-baa8-04ad9cfccf49">


The picture on one page is not converted into webp format normally, which is very strange

beforeBundle: false,
            // Default mode squoosh. support squoosh and sharp
            mode: 'sharp',
            // Default configuration options for compressing different pictures
            compress: {
                jpg: {
                    quality: 70,
                },
                jpeg: {
                    quality: 70,
                },
                png: {
                    quality: 70,
                },
                webp: {
                    quality: 100,
                },
            },
            conversion: [
                { from: 'png', to: 'webp' }
            ]

**Comment by ErKeLost** [comment]
Update the version and try it. If it doesn't work, change beforeBundle to true.  latest Version 0.5.0

These are two sets of bundle logic. I can't reproduce it without demo now. You feel like you haven't got the ext suffix, but it shouldn't be like this. If you try and it still doesn't work, can you upload a demo? thank you.
